write_endpoint: azure_ai_search

endpoints:

#Azure endpoints
  azure_ai_search:
    enabled: true
    api_key_env: AZURE_VECTOR_SEARCH_API_KEY
    api_endpoint_env: AZURE_VECTOR_SEARCH_ENDPOINT
    index_name: sos-sms-index
    db_type: azure_ai_search

  azure_ai_search_backup:
    enabled: false
    api_key_env: AZURE_VECTOR_SEARCH_API_KEY_BACKUP
    api_endpoint_env: AZURE_VECTOR_SEARCH_ENDPOINT_BACKUP
    index_name: embeddings1536
    db_type: azure_ai_search
    name: NLWeb_Crawl_Backup

  